
(function(){
const C=window.CATALOG||[];
const path=location.pathname;
const depth=(path.includes('/apps/')||path.includes('/esde/')||path.includes('/recursos/'))?'../':'';
function img(src){return depth+src}
function href(id){return depth+'item.html?id='+encodeURIComponent(id)}
function statusText(s){return {'Disponible':'🟢 Disponible','Nou':'🔵 Nou','En proves':'🟡 En proves','En construcció':'🔴 En construcció'}[s]||s}
function card(it){return `<a class="cover-card" data-area="${(it.area||[]).join(' ')}" data-sub="${it.sub}" data-name="${it.nom.toLowerCase()}" href="${href(it.id)}"><span class="status">${statusText(it.estat)}</span><img src="${img(it.cover)}" alt="${it.nom}"><div class="overlay"><h3>${it.nom}</h3><div class="meta"><span class="pill">${it.sub}</span><span class="pill">${it.tipus}</span><span class="pill">${it.duracio}</span></div><p>${it.desc}</p><span class="btn">Obrir</span></div></a>`}
function row(title, list, cls=''){return `<section class="platform-row"><div class="subbanner ${cls}"><h2>${title}</h2></div><div class="covers">${list.map(card).join('')}</div></section>`}
function renderSection(section){let el=document.querySelector('[data-section]'); if(!el)return; let data=C.filter(x=>x.section===section); let groups=[...new Set(data.map(x=>x.sub))]; el.innerHTML=groups.map(g=>row(g,data.filter(x=>x.sub===g), section==='esde'?'esde':section==='recursos'?'recursos':'' )).join(''); setupFilters(data, el);}
function setupFilters(data, container){const tools=document.querySelector('[data-tools]'); if(!tools)return; const areas=[...new Set(data.flatMap(x=>x.area||[]))].slice(0,12); tools.innerHTML=`<input class="search" placeholder="Buscar..." data-search>`+['Totes',...areas].map(a=>`<button class="filter ${a==='Totes'?'active':''}" data-filter="${a}">${a}</button>`).join(''); const input=tools.querySelector('[data-search]'); const filters=tools.querySelectorAll('[data-filter]'); let current='Totes'; function apply(){let q=(input.value||'').toLowerCase(); container.querySelectorAll('.cover-card').forEach(c=>{let okq=!q||c.dataset.name.includes(q);let oka=current==='Totes'||c.dataset.area.includes(current);c.classList.toggle('hidden',!(okq&&oka));});} input.oninput=apply; filters.forEach(b=>b.onclick=()=>{filters.forEach(x=>x.classList.remove('active'));b.classList.add('active');current=b.dataset.filter;apply();});}
function renderHome(){let h=document.querySelector('[data-home]'); if(!h)return; const latest=C.slice(-6).reverse(); const featured=C.filter(x=>(x.badges||[]).includes('Destacat')).slice(0,6); const trend=C.filter(x=>(x.badges||[]).includes('Tendència')).slice(0,6); const stats=document.querySelector('[data-stats]'); if(stats){stats.innerHTML=`<div class="stat"><b>${C.filter(x=>x.section==='apps').length}</b>Apps</div><div class="stat"><b>${C.filter(x=>x.section==='esde').length}</b>ESDE</div><div class="stat"><b>${C.filter(x=>x.section==='recursos').length}</b>Recursos</div><div class="stat"><b>${C.length}</b>Total</div>`} h.innerHTML=row('🔥 Novetats',latest)+row('⭐ Destacats',featured)+row('📈 Tendència',trend);}
function renderDetail(){let box=document.querySelector('[data-detail]'); if(!box)return; let id=new URLSearchParams(location.search).get('id')||C[0].id; let it=C.find(x=>x.id===id)||C[0]; document.title=it.nom+' · CHUK90'; let related=C.filter(x=>x.id!==it.id && (x.section===it.section || x.sub===it.sub)).slice(0,3); let mainBtn=it.section==='recursos'?`<a class="btn" href="${depth+it.url}">👁️ Veure</a><a class="btn secondary" href="${depth+it.url}" download>📥 Descarregar</a>`:`<a class="btn" target="_blank" href="${depth+it.url}">▶ Obrir</a>`; box.innerHTML=`<a class="btn secondary" href="${depth+it.section}/index.html">← Tornar</a><div class="detail"><div><img class="detail-cover" src="${img(it.cover)}" alt="${it.nom}"><div class="tools"><button class="btn secondary" data-fav="${it.id}">⭐ Favorit</button></div></div><div class="panel"><h1 class="page-title">${it.nom}</h1><p class="lead">${it.desc}</p><div class="quick"><div class="q"><small>Categoria</small>${it.sub}</div><div class="q"><small>Etapa</small>${it.etapa.join(', ')}</div><div class="q"><small>Temps</small>${it.duracio}</div><div class="q"><small>Àrea</small>${it.area.join(', ')}</div><div class="q"><small>Idioma</small>${it.idioma.join(', ')}</div><div class="q"><small>Estat</small>${statusText(it.estat)}</div></div><div class="tools">${mainBtn}</div><div class="gallery">Galeria lliscant de captures — preparada per afegir imatges quan existisquen.</div><div class="accord"><details open><summary>Què treballa</summary><p>${(it.treballa||[]).join(', ')}</p></details><details><summary>Com utilitzar-lo</summary><p>${it.com}</p></details><details><summary>Cursos recomanats</summary><p>${it.cursos.join(', ')}</p></details><details><summary>Notes docents</summary><p>${it.notes}</p></details></div></div></div><section class="platform-row"><div class="row-head"><h2>També et pot interessar</h2></div><div class="covers">${related.map(card).join('')}</div></section>`; document.querySelector('[data-fav]')?.addEventListener('click',e=>{let fav=JSON.parse(localStorage.getItem('chuk90fav')||'[]'); if(!fav.includes(it.id))fav.push(it.id); localStorage.setItem('chuk90fav',JSON.stringify(fav)); e.target.textContent='⭐ Guardat';});}
document.addEventListener('DOMContentLoaded',()=>{renderHome(); renderSection(document.body.dataset.section); renderDetail();});
})();
